# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: 

jobs:

  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: install
      run: go install golang.org/x/mobile/cmd/gomobile@latest

    - name: test
      run: gomobile init

    - name: start
      run: sh ./fetch-web.sh

    - name: bud
      run: gomobile bind -target ios -bundleid {你的bundleid} -o {alist-expo仓库目录}/ios/alist/Alistlib.xcframework -ldflags "-s -w" github.com/alist-org/alist/v3/alistlib
